name = "gachawikiapi"
compatibility_date = "2024-01-01"
main = "build/worker/shim.mjs"

routes = [{ pattern = "api.gachawiki.info/*", zone_name = "gachawiki.info" }]

[build]
command = "worker-build --release"
